# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-01-26 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_course_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(default='\u5f00\u53d1', max_length=30, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0'),
        ),
    ]
