# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-02-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20180127_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_banner',
            field=models.BooleanField(default=False, verbose_name='\u5e7f\u544a\u8f6e\u64ad'),
        ),
    ]
